# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
#relative_permalinks: true
#markdown: kramdown
#theme: minima
#plugins:
#  - jekyll-feed


# Setup
title:               Lourenço Alves Pereira, Ph.D.
tagline:             ''
description:         '<img height="256" src="/public/me.png" />'
url:                 https://ljr.github.io
baseurl:             'https://ljr.github.io'
paginate:            5

# About/contact
author:
  name:              Lourenço Alves Pereira Jr
  url:               https://ljr.github.io
  email:             ljr [at] ita.br

# Custom vars
version:             1.0.0
plugins: [jekyll-paginate]
